### ISSUE TITLE
feat: #7 이벤트 페이지 제작

### ISSUE THREAD

**Issue by quswjdgma83** [Kpop-Goods/Kg-FE#7]
## 기능 정의

- 이벤트 페이지 제작

<br>

## 작업 상세 내용

- [ ] TODO

<br>

**Comment by ijaesin** [comment]
정흠님 해당 이슈는 7번입니다 !
PR도 번호를 할당 받으니 이 부분 혼동 안하시게 유의하시면 됩니다
